include ../Makefile.project_common

APPLICATION = botones_prueba

BOARD ?= native

RIOTBASE ?= $(CUDIR)/../..

FEATURES_REQUIRED += periph_gpio_irq
USEMODULE += xtimer

TEST_ON_CI_WHITELIST += all

DEVELHELP ?= 1

QUIET ?= 1

include $(RIOTBASE)/Makefile.include
